version: "3.9"
services:
  web:
    build: .
    ports:
      - 8000:8000
    command: gunicorn f1store.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code  
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-ajuk-2^1p04sk6eu8u^obwxazo9_yd=%470h7h6r!=$$!25))n="
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "STRIPE_SECRET_KEY=sk_test_51M9FBBHResVY53M8xlH5qKlAOJK8kxzCdzNTTvs0BRpXs5uCNuxDdfNBUarjDUZJKNeb8E5C4HvfvweDX8uaM53e00D01YoehX"
      - "SECURE_SSL_REDIRECT=False"
      - "SECURE_HSTS_SECONDS=0"
      - "SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "SECURE_HSTS_PRELOAD=False"
      - "SESSION_COOKIE_SECURE=False"
      - "CSRF_COOKIE_SECURE=False"
      - "S3_ENABLED=False"
      - "LOCAL_SERVE_MEDIA_FILES=True"
      - "LOCAL_SERVE_STATIC_FILES=True"
  db:
    image: postgres:13.4-alpine
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
