# Generated by Django 4.1.2 on 2022-11-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='logo',
            new_name='image',
        ),
    ]
