# Generated by Django 4.1.2 on 2022-12-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_review_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
    ]
