# Generated by Django 4.1.2 on 2022-11-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='place',
            new_name='street',
        ),
    ]
